add replit code
marella/ctransformers pull request #37
Opened 2023-06-27 21:37 UTC by abacaj

Added replit it code. Majority of the changes were taken from the original impl found on ggml. Have it working here: https://github.com/abacaj/replit-3B-inference

2023-06-29 18:34 UTC, marella requested changes
Thanks. Do you have a link to download model that I can use for testing.

2023-06-29 18:34 UTC, marella commented on setup.py
> +    version="0.2.11",
This change is not required. I will update this before releasing a new version.

2023-06-29 18:34 UTC, marella commented on models/llms/replit.cc
> +  mutable std::string current_word_;
Nit: You can call it something like `detokenized_text_` to make it easier to understand that it is used by detokenize method.

2023-06-29 18:55 UTC, abacaj commented
> Thanks. Do you have a link to download model that I can use for testing.

Hi yes, model is hosted here: https://huggingface.co/abacaj/Replit-v2-CodeInstruct-3B-ggml. Will make the other changes you mentioned

2023-06-29 19:36 UTC, marella requested changes

2023-06-29 19:36 UTC, marella commented on models/llms/replit.cc
> +    return true;
You can now remove the `IsEosToken`, `EosToken`, `VocabSize`, `VocabSize`, `Sample` methods as they are now same as the base methods.

2023-06-29 19:37 UTC, marella commented
> > Thanks. Do you have a link to download model that I can use for testing.
> 
> Hi yes, model is hosted here: https://huggingface.co/abacaj/Replit-v2-CodeInstruct-3B-ggml. Will make the other changes you mentioned

Thanks, I will test this tomorrow.

2023-07-03 18:20 UTC, marella approved these changes

2023-07-03 18:20 UTC, merged